[SERVICE]
    Flush         1
    Log_Level     info

[INPUT]
    Name              tail
    Path              /logs/app.log
    Tag               qa.demo
    Parser            json
    DB                /state/fluent-bit.db
    Read_from_Head    true
    Refresh_Interval  2
    Skip_Long_Lines   On

[OUTPUT]
    Name                es
    Match               qa.*
    Host                elasticsearch
    Port                9200
    Logstash_Format     On
    Logstash_Prefix     qa-demo
    Suppress_Type_Name  On
    Generate_ID         On
    Retry_Limit         False
